//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace PKG_WS_CMBD.PKG_WS_CMBD {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PKG_WS_CMBDBinding", Namespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD")]
    public partial class PKG_WS_CMBDService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WS004_EPISODIO_POR_NEPISOperationCompleted;
        
        private System.Threading.SendOrPostCallback WS003_EPISODIOS_POR_NDNIOperationCompleted;
        
        private System.Threading.SendOrPostCallback WS002_EPISODIOS_POR_NHISTOperationCompleted;
        
        private System.Threading.SendOrPostCallback WS001_EPISODIOS_POR_NUHSAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PKG_WS_CMBDService() {
            this.Url = global::PKG_WS_CMBD.Properties.Settings.Default.PKG_WS_CMBD_PKG_WS_CMBD_PKG_WS_CMBDService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WS004_EPISODIO_POR_NEPISCompletedEventHandler WS004_EPISODIO_POR_NEPISCompleted;
        
        /// <remarks/>
        public event WS003_EPISODIOS_POR_NDNICompletedEventHandler WS003_EPISODIOS_POR_NDNICompleted;
        
        /// <remarks/>
        public event WS002_EPISODIOS_POR_NHISTCompletedEventHandler WS002_EPISODIOS_POR_NHISTCompleted;
        
        /// <remarks/>
        public event WS001_EPISODIOS_POR_NUHSACompletedEventHandler WS001_EPISODIOS_POR_NUHSACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WS004_EPISODIO_POR_NEPIS", RequestElementName="S-WS004_EPISODIO_POR_NEPISInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD", ResponseElementName="WS004_EPISODIO_POR_NEPISOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WS004_EPISODIO_POR_NEPIS(System.Xml.XmlElement RETURN) {
            this.Invoke("WS004_EPISODIO_POR_NEPIS", new object[] {
                        RETURN});
        }
        
        /// <remarks/>
        public void WS004_EPISODIO_POR_NEPISAsync(System.Xml.XmlElement RETURN) {
            this.WS004_EPISODIO_POR_NEPISAsync(RETURN, null);
        }
        
        /// <remarks/>
        public void WS004_EPISODIO_POR_NEPISAsync(System.Xml.XmlElement RETURN, object userState) {
            if ((this.WS004_EPISODIO_POR_NEPISOperationCompleted == null)) {
                this.WS004_EPISODIO_POR_NEPISOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS004_EPISODIO_POR_NEPISOperationCompleted);
            }
            this.InvokeAsync("WS004_EPISODIO_POR_NEPIS", new object[] {
                        RETURN}, this.WS004_EPISODIO_POR_NEPISOperationCompleted, userState);
        }
        
        private void OnWS004_EPISODIO_POR_NEPISOperationCompleted(object arg) {
            if ((this.WS004_EPISODIO_POR_NEPISCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS004_EPISODIO_POR_NEPISCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WS003_EPISODIOS_POR_NDNI", RequestElementName="S-WS003_EPISODIOS_POR_NDNIInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD", ResponseElementName="WS003_EPISODIOS_POR_NDNIOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WS003_EPISODIOS_POR_NDNI(System.Xml.XmlElement RETURN) {
            this.Invoke("WS003_EPISODIOS_POR_NDNI", new object[] {
                        RETURN});
        }
        
        /// <remarks/>
        public void WS003_EPISODIOS_POR_NDNIAsync(System.Xml.XmlElement RETURN) {
            this.WS003_EPISODIOS_POR_NDNIAsync(RETURN, null);
        }
        
        /// <remarks/>
        public void WS003_EPISODIOS_POR_NDNIAsync(System.Xml.XmlElement RETURN, object userState) {
            if ((this.WS003_EPISODIOS_POR_NDNIOperationCompleted == null)) {
                this.WS003_EPISODIOS_POR_NDNIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS003_EPISODIOS_POR_NDNIOperationCompleted);
            }
            this.InvokeAsync("WS003_EPISODIOS_POR_NDNI", new object[] {
                        RETURN}, this.WS003_EPISODIOS_POR_NDNIOperationCompleted, userState);
        }
        
        private void OnWS003_EPISODIOS_POR_NDNIOperationCompleted(object arg) {
            if ((this.WS003_EPISODIOS_POR_NDNICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS003_EPISODIOS_POR_NDNICompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WS002_EPISODIOS_POR_NHIST", RequestElementName="S-WS002_EPISODIOS_POR_NHISTInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD", ResponseElementName="WS002_EPISODIOS_POR_NHISTOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WS002_EPISODIOS_POR_NHIST(System.Xml.XmlElement RETURN) {
            this.Invoke("WS002_EPISODIOS_POR_NHIST", new object[] {
                        RETURN});
        }
        
        /// <remarks/>
        public void WS002_EPISODIOS_POR_NHISTAsync(System.Xml.XmlElement RETURN) {
            this.WS002_EPISODIOS_POR_NHISTAsync(RETURN, null);
        }
        
        /// <remarks/>
        public void WS002_EPISODIOS_POR_NHISTAsync(System.Xml.XmlElement RETURN, object userState) {
            if ((this.WS002_EPISODIOS_POR_NHISTOperationCompleted == null)) {
                this.WS002_EPISODIOS_POR_NHISTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS002_EPISODIOS_POR_NHISTOperationCompleted);
            }
            this.InvokeAsync("WS002_EPISODIOS_POR_NHIST", new object[] {
                        RETURN}, this.WS002_EPISODIOS_POR_NHISTOperationCompleted, userState);
        }
        
        private void OnWS002_EPISODIOS_POR_NHISTOperationCompleted(object arg) {
            if ((this.WS002_EPISODIOS_POR_NHISTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS002_EPISODIOS_POR_NHISTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WS001_EPISODIOS_POR_NUHSA", RequestElementName="WS001_EPISODIOS_POR_NUHSAInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD", ResponseElementName="WS001_EPISODIOS_POR_NUHSAOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RO/PKG_WS_CMBD", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("P_RESULTADO")]
        public System.Xml.XmlElement WS001_EPISODIOS_POR_NUHSA([System.Xml.Serialization.XmlElementAttribute("P_RESULTADO-XMLTYPE-OUT")] WS001_EPISODIOS_POR_NUHSAInputP_RESULTADOXMLTYPEOUT P_RESULTADOXMLTYPEOUT, [System.Xml.Serialization.XmlElementAttribute("P_NUHSA-VARCHAR2-IN")] string P_NUHSAVARCHAR2IN) {
            object[] results = this.Invoke("WS001_EPISODIOS_POR_NUHSA", new object[] {
                        P_RESULTADOXMLTYPEOUT,
                        P_NUHSAVARCHAR2IN});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void WS001_EPISODIOS_POR_NUHSAAsync(WS001_EPISODIOS_POR_NUHSAInputP_RESULTADOXMLTYPEOUT P_RESULTADOXMLTYPEOUT, string P_NUHSAVARCHAR2IN) {
            this.WS001_EPISODIOS_POR_NUHSAAsync(P_RESULTADOXMLTYPEOUT, P_NUHSAVARCHAR2IN, null);
        }
        
        /// <remarks/>
        public void WS001_EPISODIOS_POR_NUHSAAsync(WS001_EPISODIOS_POR_NUHSAInputP_RESULTADOXMLTYPEOUT P_RESULTADOXMLTYPEOUT, string P_NUHSAVARCHAR2IN, object userState) {
            if ((this.WS001_EPISODIOS_POR_NUHSAOperationCompleted == null)) {
                this.WS001_EPISODIOS_POR_NUHSAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS001_EPISODIOS_POR_NUHSAOperationCompleted);
            }
            this.InvokeAsync("WS001_EPISODIOS_POR_NUHSA", new object[] {
                        P_RESULTADOXMLTYPEOUT,
                        P_NUHSAVARCHAR2IN}, this.WS001_EPISODIOS_POR_NUHSAOperationCompleted, userState);
        }
        
        private void OnWS001_EPISODIOS_POR_NUHSAOperationCompleted(object arg) {
            if ((this.WS001_EPISODIOS_POR_NUHSACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS001_EPISODIOS_POR_NUHSACompleted(this, new WS001_EPISODIOS_POR_NUHSACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WS001_EPISODIOS_POR_NUHSAInputP_RESULTADOXMLTYPEOUT {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void WS004_EPISODIO_POR_NEPISCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void WS003_EPISODIOS_POR_NDNICompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void WS002_EPISODIOS_POR_NHISTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void WS001_EPISODIOS_POR_NUHSACompletedEventHandler(object sender, WS001_EPISODIOS_POR_NUHSACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WS001_EPISODIOS_POR_NUHSACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WS001_EPISODIOS_POR_NUHSACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591