//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace PKG_WS_CMBD.PKG_WS_UPDX_DESA {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PKG_WS_UPDXBinding", Namespace="http://xmlns.oracle.com/orawsv/WS_RW/PKG_WS_UPDX")]
    public partial class PKG_WS_UPDXService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback WS001_MODIFICA_COD_SINOOperationCompleted;
        
        private System.Threading.SendOrPostCallback WRITE_LOPDOperationCompleted;
        
        private System.Threading.SendOrPostCallback START_UPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PKG_WS_UPDXService() {
            this.Url = global::PKG_WS_CMBD.Properties.Settings.Default.PKG_WS_CMBD_PKG_WS_UPDX_DESA_PKG_WS_UPDXService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event WS001_MODIFICA_COD_SINOCompletedEventHandler WS001_MODIFICA_COD_SINOCompleted;
        
        /// <remarks/>
        public event WRITE_LOPDCompletedEventHandler WRITE_LOPDCompleted;
        
        /// <remarks/>
        public event START_UPCompletedEventHandler START_UPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WS001_MODIFICA_COD_SINO", RequestElementName="WS001_MODIFICA_COD_SINOInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RW/PKG_WS_UPDX", ResponseElementName="WS001_MODIFICA_COD_SINOOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RW/PKG_WS_UPDX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("P_RESULTADO")]
        public System.Xml.XmlElement WS001_MODIFICA_COD_SINO([System.Xml.Serialization.XmlElementAttribute("P_RESULTADO-XMLTYPE-OUT")] WS001_MODIFICA_COD_SINOInputP_RESULTADOXMLTYPEOUT P_RESULTADOXMLTYPEOUT, [System.Xml.Serialization.XmlElementAttribute("P_QUIENERES-VARCHAR2-IN")] string P_QUIENERESVARCHAR2IN, [System.Xml.Serialization.XmlElementAttribute("P_NADMI-NUMBER-IN")] double P_NADMINUMBERIN, [System.Xml.Serialization.XmlElementAttribute("P_CAMPOS-VARCHAR2-OUT")] WS001_MODIFICA_COD_SINOInputP_CAMPOSVARCHAR2OUT P_CAMPOSVARCHAR2OUT, out string P_CAMPOS) {
            object[] results = this.Invoke("WS001_MODIFICA_COD_SINO", new object[] {
                        P_RESULTADOXMLTYPEOUT,
                        P_QUIENERESVARCHAR2IN,
                        P_NADMINUMBERIN,
                        P_CAMPOSVARCHAR2OUT});
            P_CAMPOS = ((string)(results[1]));
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void WS001_MODIFICA_COD_SINOAsync(WS001_MODIFICA_COD_SINOInputP_RESULTADOXMLTYPEOUT P_RESULTADOXMLTYPEOUT, string P_QUIENERESVARCHAR2IN, double P_NADMINUMBERIN, WS001_MODIFICA_COD_SINOInputP_CAMPOSVARCHAR2OUT P_CAMPOSVARCHAR2OUT) {
            this.WS001_MODIFICA_COD_SINOAsync(P_RESULTADOXMLTYPEOUT, P_QUIENERESVARCHAR2IN, P_NADMINUMBERIN, P_CAMPOSVARCHAR2OUT, null);
        }
        
        /// <remarks/>
        public void WS001_MODIFICA_COD_SINOAsync(WS001_MODIFICA_COD_SINOInputP_RESULTADOXMLTYPEOUT P_RESULTADOXMLTYPEOUT, string P_QUIENERESVARCHAR2IN, double P_NADMINUMBERIN, WS001_MODIFICA_COD_SINOInputP_CAMPOSVARCHAR2OUT P_CAMPOSVARCHAR2OUT, object userState) {
            if ((this.WS001_MODIFICA_COD_SINOOperationCompleted == null)) {
                this.WS001_MODIFICA_COD_SINOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWS001_MODIFICA_COD_SINOOperationCompleted);
            }
            this.InvokeAsync("WS001_MODIFICA_COD_SINO", new object[] {
                        P_RESULTADOXMLTYPEOUT,
                        P_QUIENERESVARCHAR2IN,
                        P_NADMINUMBERIN,
                        P_CAMPOSVARCHAR2OUT}, this.WS001_MODIFICA_COD_SINOOperationCompleted, userState);
        }
        
        private void OnWS001_MODIFICA_COD_SINOOperationCompleted(object arg) {
            if ((this.WS001_MODIFICA_COD_SINOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WS001_MODIFICA_COD_SINOCompleted(this, new WS001_MODIFICA_COD_SINOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WRITE_LOPD", RequestElementName="WRITE_LOPDInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RW/PKG_WS_UPDX", ResponseElementName="WRITE_LOPDOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RW/PKG_WS_UPDX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void WRITE_LOPD([System.Xml.Serialization.XmlElementAttribute("P_RESULTADO-XMLTYPE-IN")] System.Xml.XmlElement P_RESULTADOXMLTYPEIN, [System.Xml.Serialization.XmlElementAttribute("P_QUIENERES-VARCHAR2-IN")] string P_QUIENERESVARCHAR2IN, [System.Xml.Serialization.XmlElementAttribute("P_INPUT-VARCHAR2-IN")] string P_INPUTVARCHAR2IN) {
            this.Invoke("WRITE_LOPD", new object[] {
                        P_RESULTADOXMLTYPEIN,
                        P_QUIENERESVARCHAR2IN,
                        P_INPUTVARCHAR2IN});
        }
        
        /// <remarks/>
        public void WRITE_LOPDAsync(System.Xml.XmlElement P_RESULTADOXMLTYPEIN, string P_QUIENERESVARCHAR2IN, string P_INPUTVARCHAR2IN) {
            this.WRITE_LOPDAsync(P_RESULTADOXMLTYPEIN, P_QUIENERESVARCHAR2IN, P_INPUTVARCHAR2IN, null);
        }
        
        /// <remarks/>
        public void WRITE_LOPDAsync(System.Xml.XmlElement P_RESULTADOXMLTYPEIN, string P_QUIENERESVARCHAR2IN, string P_INPUTVARCHAR2IN, object userState) {
            if ((this.WRITE_LOPDOperationCompleted == null)) {
                this.WRITE_LOPDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWRITE_LOPDOperationCompleted);
            }
            this.InvokeAsync("WRITE_LOPD", new object[] {
                        P_RESULTADOXMLTYPEIN,
                        P_QUIENERESVARCHAR2IN,
                        P_INPUTVARCHAR2IN}, this.WRITE_LOPDOperationCompleted, userState);
        }
        
        private void OnWRITE_LOPDOperationCompleted(object arg) {
            if ((this.WRITE_LOPDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WRITE_LOPDCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("START_UP", RequestElementName="START_UPInput", RequestNamespace="http://xmlns.oracle.com/orawsv/WS_RW/PKG_WS_UPDX", ResponseElementName="START_UPOutput", ResponseNamespace="http://xmlns.oracle.com/orawsv/WS_RW/PKG_WS_UPDX", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void START_UP([System.Xml.Serialization.XmlElementAttribute("P_QUIENERES-VARCHAR2-IN")] string P_QUIENERESVARCHAR2IN) {
            this.Invoke("START_UP", new object[] {
                        P_QUIENERESVARCHAR2IN});
        }
        
        /// <remarks/>
        public void START_UPAsync(string P_QUIENERESVARCHAR2IN) {
            this.START_UPAsync(P_QUIENERESVARCHAR2IN, null);
        }
        
        /// <remarks/>
        public void START_UPAsync(string P_QUIENERESVARCHAR2IN, object userState) {
            if ((this.START_UPOperationCompleted == null)) {
                this.START_UPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSTART_UPOperationCompleted);
            }
            this.InvokeAsync("START_UP", new object[] {
                        P_QUIENERESVARCHAR2IN}, this.START_UPOperationCompleted, userState);
        }
        
        private void OnSTART_UPOperationCompleted(object arg) {
            if ((this.START_UPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.START_UPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WS001_MODIFICA_COD_SINOInputP_RESULTADOXMLTYPEOUT {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class WS001_MODIFICA_COD_SINOInputP_CAMPOSVARCHAR2OUT {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void WS001_MODIFICA_COD_SINOCompletedEventHandler(object sender, WS001_MODIFICA_COD_SINOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WS001_MODIFICA_COD_SINOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal WS001_MODIFICA_COD_SINOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string P_CAMPOS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void WRITE_LOPDCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void START_UPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591