//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PKG_WS_CMBD.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fraterno:8181/orawsv/WS_RO/PKG_WS_CMBD")]
        public string PKG_WS_CMBD_PKG_WS_CMBD_PROD_PKG_WS_CMBDService {
            get {
                return ((string)(this["PKG_WS_CMBD_PKG_WS_CMBD_PROD_PKG_WS_CMBDService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bertoaldo.valme.net:8181/orawsv/WS_RO/PKG_WS_CMBD")]
        public string PKG_WS_CMBD_PKG_WS_CMBD_PKG_WS_CMBDService {
            get {
                return ((string)(this["PKG_WS_CMBD_PKG_WS_CMBD_PKG_WS_CMBDService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://bertoaldo.valme.net:8181/orawsv/WS_RW/PKG_WS_UPDX")]
        public string PKG_WS_CMBD_PKG_WS_UPDX_DESA_PKG_WS_UPDXService {
            get {
                return ((string)(this["PKG_WS_CMBD_PKG_WS_UPDX_DESA_PKG_WS_UPDXService"]));
            }
        }
    }
}
